### ISSUE TITLE
Save frequency and use it for filling

### ISSUE THREAD

**Issue by jayanthkmr** [cdli-gh/morphology-pre-annotation-tool#1]
To do:
1. Store the frequencies of the tuple of lemma and postag
2. Use the frequencies to fill it

**Comment by jayanthkmr** [comment]
Done with https://github.com/cdli-gh/morphology-pre-annotation-tool/pull/13.

**Comment by jayanthkmr** [comment]
@epageperron Please test.

**Comment by epageperron** [comment]
Works !
