### ISSUE TITLE
Show alternate annotation possibilities in subsequent column, ordered by freq

### ISSUE THREAD

**Issue by epageperron** [cdli-gh/morphology-pre-annotation-tool#11]
When the dictionary has more than one possibility of annotation for a form, use the most frequent option in the usual place and add alternate options, by frequency order, in the following columns

**Comment by jayanthkmr** [comment]
@epageperron Done. Please test. New version - 0.1.6.

**Comment by epageperron** [comment]
Can we say that if frequency is equal, to use the entry with the shortest XPOSTAG content?

**Comment by epageperron** [comment]
In fact let's use it more before as I don't have a good sample to know with certainty that the shorter is best than the first in the list ( it was in the texts I tested with though). Some entries in ETCSRI are not fully tagged so it might just result in suggesting untagged forms when it would be easier to work from one of the tagged options.
