### ISSUE TITLE
can't learn from folder?

### ISSUE THREAD

**Issue by epageperron** [cdli-gh/morphology-pre-annotation-tool#12]
Apparently the pre annotation tool will now only learn from a file, not from a folder. 

Do we need to use the --no-output switch for it to work?

**Comment by jayanthkmr** [comment]
To check if the folder is being learned.

**Comment by jayanthkmr** [comment]
@epageperron it is learning from folder. Please check again. It picks the file one by one from the folder and updates the dictionary.

**Comment by epageperron** [comment]
works perfectly!
