### ISSUE TITLE
remove <> from form

### ISSUE THREAD

**Issue by epageperron** [cdli-gh/morphology-pre-annotation-tool#17]
Before tokenizing/creating the form column, also remove  < and > just like the square brackets and hash are removed, also ! and ?

**Comment by jayanthkmr** [comment]
@epageperron should this be part of this tool or [atf2conll](https://github.com/cdli-gh/atf2conll-convertor)?

**Comment by epageperron** [comment]
yes ! will move the issue

**Comment by epageperron** [comment]
This issue was moved to cdli-gh/atf2conll-convertor#7
