### ISSUE TITLE
clear the dictionary

### ISSUE THREAD

**Issue by epageperron** [cdli-gh/morphology-pre-annotation-tool#19]
Spotlight won't find the dictionary on my mac, it's not in my home dir, and I can't see the home dir for "root" in the GUI. Can we add a command that will clear the dictionary? Or is there an easy way for me to find and delete the dictionary? Also I don't know if I am searching for the original dic name or v2 dic? Maybe we could just have the same filename for any version.  Help ! 

The problem arises because I have been working a bit on making the annotated texts more consistent, and now I have 13 texts to pre-annotate but I cannot reset my dictionary. I updated it with the latest annotated texts but I can't remove the legacy bad entries. I only have this issue on the mac as on my linux box I can locate and delete the dict easily.

**Comment by jayanthkmr** [comment]
feature added to delete - https://github.com/cdli-gh/morphology-pre-annotation-tool/commit/b03ef2029762409032e18288a3e73fd1a95a8086. test and close.:

To delete the stored dictionary, use the --delete_dict/-d switch:
```
$ mpat -d
```

**Comment by epageperron** [comment]
Works !
