### ISSUE TITLE
Detect if content annotated or not and keep .conll extension

### ISSUE THREAD

**Issue by epageperron** [cdli-gh/morphology-pre-annotation-tool#2]
Let's check if there is information in the annotation fields, if not then fill, if yes, then learn.

**Comment by jayanthkmr** [comment]
@epageperron Added --no_output for only filling the dictionary.

**Comment by jayanthkmr** [comment]
@epageperron It should be closed. Let me know, if I din't understand anything.

**Comment by epageperron** [comment]
I am not sure how to use the flag as I get an error when I use it but apparently the tool can now see if the file needs to be learned from or annotated?
