### ISSUE TITLE
Intergrate the ATF to CoNLL converter in this tool

### ISSUE THREAD

**Issue by epageperron** [cdli-gh/morphology-pre-annotation-tool#3]
In order to streamline our tools, let's integrate the ATF converter. It is, after all, converted with the purpose of allowing annotation.

**Comment by epageperron** [comment]
lower priority

**Comment by epageperron** [comment]
tools will stay separate as per @jayanthjaiswal

**Comment by jayanthkmr** [comment]
Seperated here - https://github.com/cdli-gh/atf2conll-convertor
